apiVersion: apps/v1
kind: Deployment
metadata:
  name: giftapp
  labels:
    app: giftapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: giftapp
  template:
    metadata:
      labels:
        app: giftapp
    spec:
      containers:
      - name: giftapp-container
        image: <ECR_URL>/giftapp-backend:latest   # ✅ 這裡換成你的 ECR Image
        ports:
        - containerPort: 3060
      imagePullSecrets:
      - name: aws-ecr-secret  # ✅ 確保有 `kubectl create secret` 建立 AWS ECR 授權

---
apiVersion: v1
kind: Service
metadata:
  name: gift-app-service
spec:
  type: LoadBalancer  # ✅ 使用 LoadBalancer 取代 NodePort
  ports:
  - port: 80
    targetPort: 3060
    protocol: TCP
  selector:
    app: giftapp
