apiVersion: apps/v1
kind: Deployment
metadata:
  name: giftapp
  labels:
    app: giftapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: giftapp
  template:
    metadata:
      labels:
        app: giftapp
    spec:
      serviceAccountName: ecr-access  # ✅ 確保 EKS 叢集的 Pod 使用正確的 IAM 角色
      containers:
      - name: giftapp-container
        image: <ECR_URL>/giftapp-backend:latest   # ✅ 這裡換成你的 ECR Image
        ports:
        - containerPort: 3060
      imagePullSecrets:
      - name: aws-ecr-secret

---
apiVersion: v1
kind: Service
metadata:
  name: gift-app-service
spec:
  type: LoadBalancer  # ✅ 使用 LoadBalancer 取代 NodePort
  ports:
  - port: 80
    targetPort: 3060
    protocol: TCP
  selector:
    app: giftapp
