name: Deploy to AWS

on:
  push:
    branches:
      - main  # 當 push 到 main 分支時觸發部署

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 🚀 檢出程式碼
      uses: actions/checkout@v4

    - name: 🔐 設定 AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: 🛠 安裝 eksctl
      run: |
        curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
        sudo mv /tmp/eksctl /usr/local/bin
        eksctl version  # 確認 eksctl 安裝成功

    - name: 🐳 登入 AWS ECR
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPO }}
    
    - name: ⚙️ 檢查並建立 AWS EKS 叢集
      run: |
        eksctl get cluster --name giftapp-cluster || eksctl create cluster --name giftapp-cluster --region ${{ secrets.AWS_REGION }} --nodegroup-name giftapp-nodes --node-type t3.medium --nodes 2

    - name: 🔧 設定 Kubeconfig
      run: aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name giftapp-cluster

    - name: ⬆️ 部署 MongoDB 到 AWS EKS
      run: |
        kubectl apply -f ./kubernetes/deploymongo.yml

    - name: 🏗️ 建立 Backend Docker Image 並推送到 AWS ECR
      run: |
        docker build -t ${{ secrets.ECR_REPO }}/giftapp-backend:latest ./giftlink-backend
        docker push ${{ secrets.ECR_REPO }}/giftapp-backend:latest

    - name: ⬆️ 部署 MongoDB 到 AWS EKS
      run: |
        kubectl apply -f ./kubernetes/deployment.yml